# Copyright (C) 2025 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0
---
- name: Install svtrace
  ansible.builtin.pip:
    virtualenv: "{{ svtrace_venv_path }}"
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv "
    name: git+https://github.com/seapath/svtrace.git@v0.1.1
  when: enable_svtrace is defined and enable_svtrace|bool == true
- name: Send svtrace configuration file
  template:
      src: svtrace.cfg.j2
      dest: /etc/svtrace.cfg
  when: enable_svtrace is defined and enable_svtrace|bool == true
