# Copyright (C) 2025 Savoir-faire Linux, Inc.
# SPDX-License-Identifier: Apache-2.0
---
- name: set platform
  set_fact:
    target_architecture: "{{ hostvars[inventory_hostname]['target_platform'] | default(target_platform) }}"

- name: Stop hardware sv_timestamp_logger container
  become: true
  docker_container:
    name: sv_timestamp_logger_hw_{{ target_architecture }}
    state: absent

- name: Fetch hardware SV timestamps
  synchronize:
    src: "{{ ansible_user_dir }}/latency_tests/ts_hw_{{ inventory_hostname }}.txt"
    dest: ../tests_results/data/
    mode: pull
